package com.daon.futures

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Card
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.util.Locale
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

fun emaSeries(values:List<Double>,period:Int):List<Double>{if(values.isEmpty())return emptyList();val k=2.0/(period+1.0);val out=MutableList(values.size){0.0};var ema=values.first();out[0]=ema;for(i in 1 until values.size){ema=values[i]*k+ema*(1-k);out[i]=ema};return out}
fun rsiValue(values:List<Double>,period:Int=14):Double{if(values.size<=period)return 50.0;var g=0.0;var l=0.0;for(i in values.size-period until values.size){val d=values[i]-values[i-1];if(d>=0)g+=d else l-=d};if(l==0.0)return 100.0;val rs=(g/period)/(l/period);return 100-100/(1+rs)}
private data class MoneyFlowMark(val index:Int,val level:Int)
private fun moneyFlowMarks(c:List<Candle>):List<MoneyFlowMark>{if(c.size<12)return emptyList();val ranges=c.map{max(0.0,it.high-it.low)};val out=mutableListOf<MoneyFlowMark>();for(i in 10 until c.size){val base=ranges.subList(i-10,i).average().coerceAtLeast(1e-9);val impulse=ranges[i]/base;val body=abs(c[i].close-c[i].open)/base;val level=when{impulse>=2.8&&body>=1.0->3;impulse>=2.1&&body>=.65->2;impulse>=1.6&&body>=.35->1;else->0};if(level>0)out+=MoneyFlowMark(i,level)};return out.takeLast(6)}
private data class OneCandleZone(val index:Int,val low:Double,val high:Double,val side:String,val retested:Boolean,val confirmed:Boolean,val entry:Double?,val stop:Double?,val target2R:Double?)
private fun oneCandleZone(c:List<Candle>,e20:List<Double>,e50:List<Double>):OneCandleZone?{if(c.size<22||e20.isEmpty()||e50.isEmpty())return null;val bull=e20.last()>e50.last();val start=maxOf(0,c.size-21);val end=c.size-1;val indexed=(start until end).map{it to c[it]};val key=(if(bull)indexed.filter{(_,x)->x.close<x.open}.maxByOrNull{(_,x)->x.high}else indexed.filter{(_,x)->x.close>x.open}.minByOrNull{(_,x)->x.low})?:return null;val(idx,x)=key;val low=minOf(x.open,x.close);val high=maxOf(x.open,x.close);val after=c.drop(idx+1);val retested=after.any{it.low<=high&&it.high>=low};val last=c.last();val confirmed=retested&&if(bull)last.close>high else last.close<low;val side=if(bull)"LONG" else "SHORT";if(!confirmed)return OneCandleZone(idx,low,high,side,retested,false,null,null,null);val entry=last.close;val stop=if(bull)low else high;val risk=if(bull)entry-stop else stop-entry;if(risk<=0)return OneCandleZone(idx,low,high,side,retested,false,null,null,null);return OneCandleZone(idx,low,high,side,true,true,entry,stop,if(bull)entry+risk*2 else entry-risk*2)}

@Composable fun MarketChartCard(symbol:String,intervalLabel:String,candles:List<Candle>,modifier:Modifier=Modifier,exchange:String="MARKET"){
 val visible=if(candles.size>60)candles.takeLast(60) else candles;val closes=visible.map{it.close};val e20=emaSeries(closes,20);val e50=emaSeries(closes,50);val rsi=rsiValue(closes);val zone=oneCandleZone(visible,e20,e50);val marks=moneyFlowMarks(visible);val superSignal=marks.lastOrNull()?.level==3&&zone?.confirmed==true
 Card(modifier.fillMaxWidth(),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("$symbol · $intervalLabel · $exchange",fontWeight=FontWeight.Bold,fontSize=18.sp);if(visible.size<2)Text("차트 데이터를 불러오는 중입니다.",color=Color.Gray) else {Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("EMA20 ${fmtChart(e20.lastOrNull())}",color=Color(0xFF35A7FF),fontSize=13.sp);Text("EMA50 ${fmtChart(e50.lastOrNull())}",color=Color(0xFFFFA000),fontSize=13.sp);Text("RSI ${String.format(Locale.KOREA,"%.1f",rsi)}",color=Color(0xFFA875FF),fontSize=13.sp)};Text("자금유입 표시 ON · ✓ 초기  ✓✓ 추가  ★ 강한 유입",color=Color(0xFF21D58B),fontWeight=FontWeight.Bold,fontSize=12.sp);if(superSignal)Text("S SUPER SIGNAL · 강한 유입 + 진입 후보 조건",color=Color(0xFFFFC107),fontWeight=FontWeight.ExtraBold,fontSize=14.sp);zone?.let{val col=if(it.side=="LONG")Color(0xFF21D58B) else Color(0xFFFF4058);val state=when{it.confirmed->"진입 후보";it.retested->"리테스트 확인 · 방향 대기";else->"리테스트 대기"};Text("One Candle ${it.side} · 기준 ${fmtChart(it.low)} ~ ${fmtChart(it.high)} · $state",color=col,fontWeight=FontWeight.Bold,fontSize=12.sp)}?:Text("One Candle · 기준 캔들 탐색 중",color=Color.Gray,fontSize=12.sp);CandlestickCanvas(visible,e20,e50,zone,marks);zone?.takeIf{it.confirmed}?.let{Text("후보 ${fmtChart(it.entry)} · SL ${fmtChart(it.stop)} · 2R ${fmtChart(it.target2R)}",color=if(it.side=="LONG")Color(0xFF21D58B) else Color(0xFFFF4058),fontWeight=FontWeight.Bold,fontSize=12.sp)};Text("RSI 14 ${String.format(Locale.KOREA,"%.2f",rsi)}",color=Color(0xFFA875FF),fontSize=13.sp);RsiCanvas(closes)}}}}

@Composable private fun CandlestickCanvas(c:List<Candle>,e20:List<Double>,e50:List<Double>,zone:OneCandleZone?,marks:List<MoneyFlowMark>){val up=Color(0xFF18C98B);val down=Color(0xFFFF4058);Canvas(Modifier.fillMaxWidth().height(360.dp).background(Color(0xFF090E16),RoundedCornerShape(12.dp))){val extras=mutableListOf<Double>();zone?.let{extras+=it.low;extras+=it.high;it.stop?.let(extras::add);it.target2R?.let(extras::add)};val maxP=max(c.maxOf{it.high},extras.maxOrNull()?:c.maxOf{it.high});val minP=min(c.minOf{it.low},extras.minOrNull()?:c.minOf{it.low});val range=(maxP-minP).takeIf{it>0}?:1.0;val top=maxP+range*.12;val bottom=minP-range*.12;fun y(v:Double)=((top-v)/(top-bottom)*size.height).toFloat();val w=size.width*.88f;for(g in 1..5){val gy=size.height*g/6f;drawLine(Color(0xFF29313D),Offset(0f,gy),Offset(w,gy),1f)};val step=w/c.size;val bw=max(2f,step*.58f);zone?.let{val zc=if(it.side=="LONG")up else down;val left=step*it.index;val ty=min(y(it.high),y(it.low));val by=max(y(it.high),y(it.low));drawRect(zc.copy(alpha=.2f),Offset(left,ty),Size(w-left,max(3f,by-ty)))};c.forEachIndexed{i,x->val xx=step*i+step/2;val col=if(x.close>=x.open)up else down;val oy=y(x.open);val cy=y(x.close);drawLine(col,Offset(xx,y(x.high)),Offset(xx,y(x.low)),1.4f);drawRect(col,Offset(xx-bw/2,min(oy,cy)),Size(bw,max(2f,abs(cy-oy))))};fun ema(s:List<Double>,col:Color){if(s.size<2)return;val p=Path();s.forEachIndexed{i,v->val q=Offset(step*i+step/2,y(v));if(i==0)p.moveTo(q.x,q.y) else p.lineTo(q.x,q.y)};drawPath(p,col,style=Stroke(2.5f))};ema(e20,Color(0xFF2196F3));ema(e50,Color(0xFFFFA000));marks.forEach{m->val x=step*m.index+step/2;val yy=(y(c[m.index].low)+15).coerceAtMost(size.height-12);val col=if(m.level==3)Color(0xFFFFC107) else up;val r=if(m.level==3)8f else if(m.level==2)6f else 4.5f;drawCircle(col,r,Offset(x,yy))};drawLine(Color.White.copy(alpha=.35f),Offset(0f,y(c.last().close)),Offset(w,y(c.last().close)),1.2f)}}
@Composable private fun RsiCanvas(closes:List<Double>){val s=closes.indices.map{i->if(i<14)50.0 else rsiValue(closes.take(i+1),14)};Canvas(Modifier.fillMaxWidth().height(100.dp).background(Color(0xFF090E16),RoundedCornerShape(10.dp))){fun y(v:Double)=((100-v)/100*size.height).toFloat();drawLine(Color(0xFF565B66),Offset(0f,y(70.0)),Offset(size.width,y(70.0)),1f);drawLine(Color(0xFF565B66),Offset(0f,y(30.0)),Offset(size.width,y(30.0)),1f);if(s.size>1){val step=size.width/s.size;val p=Path();s.forEachIndexed{i,v->val q=Offset(step*i+step/2,y(v));if(i==0)p.moveTo(q.x,q.y) else p.lineTo(q.x,q.y)};drawPath(p,Color(0xFF8E6CFF),style=Stroke(2.4f))}}}
private fun fmtChart(v:Double?)=if(v==null)"-" else String.format(Locale.KOREA,"%,.2f",v)
