package com.daon.futures

import android.Manifest
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.pm.PackageManager
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.work.*
import java.util.concurrent.TimeUnit

class MainActivity : ComponentActivity() { private val notifPermission=registerForActivityResult(ActivityResultContracts.RequestPermission()){};override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)notifPermission.launch(Manifest.permission.POST_NOTIFICATIONS);(getSystemService(NOTIFICATION_SERVICE) as NotificationManager).createNotificationChannel(NotificationChannel("signals","캐치월드 기회 알림",NotificationManager.IMPORTANCE_HIGH));val req=PeriodicWorkRequestBuilder<SignalWorker>(15,TimeUnit.MINUTES).setConstraints(Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build()).build();WorkManager.getInstance(this).enqueueUniquePeriodicWork("catchworld-signal",ExistingPeriodicWorkPolicy.UPDATE,req);setContent{CatchWorldApp()}}}
private val Bg=Color(0xFF070B12);private val Surface=Color(0xFF111722);private val Surface2=Color(0xFF171F2C);private val Accent=Color(0xFF7A6CFF);private val Green=Color(0xFF19D38A);private val Red=Color(0xFFFF5B6E);private val Amber=Color(0xFFFFB74D);private val Muted=Color(0xFF9BA6B5)
private data class RadarModule(val name:String,val subtitle:String,val state:String,val detail:String)
@Composable fun CatchWorldApp(){var tab by remember{mutableIntStateOf(0)};val tabs=listOf("홈","레이더","차트","자산","알림");MaterialTheme(colorScheme=darkColorScheme(primary=Accent,background=Bg,surface=Surface,surfaceVariant=Surface2)){Scaffold(containerColor=Bg,bottomBar={NavigationBar(containerColor=Color(0xFF0C111A)){tabs.forEachIndexed{i,t->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={Text(listOf("⌂","◎","⌁","◆","◉")[i],fontSize=18.sp)},label={Text(t)})}}}){pad->Box(Modifier.fillMaxSize().padding(pad).background(Bg)){when(tab){0->HomeScreen();1->RadarScreen();2->ChartScreen();3->AssetScreen();else->AlertScreen()}}}}}
@Composable private fun Header(title:String,subtitle:String){Column(verticalArrangement=Arrangement.spacedBy(4.dp)){Row(verticalAlignment=Alignment.Bottom){Text(title,fontSize=28.sp,fontWeight=FontWeight.ExtraBold);Spacer(Modifier.width(8.dp));Text("v2.9",color=Accent,fontWeight=FontWeight.Bold)};Text(subtitle,color=Muted,fontSize=13.sp)}}
@Composable private fun HomeScreen(){LazyColumn(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal=14.dp),contentPadding=PaddingValues(top=14.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("캐치월드","자금유입을 먼저 찾고 검증된 진입지점을 기다리는 금융 레이더")};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){MarketChip("BTC","레이더",Modifier.weight(1f));MarketChip("금","타이밍",Modifier.weight(1f));MarketChip("ETF","탐색",Modifier.weight(1f));MarketChip("예금","비교",Modifier.weight(1f))}};item{InvestmentDashboardCard()};item{SectionTitle("신호 파이프라인")};item{OpportunityCard("✓ 자금유입 발견","가격이 크게 움직이기 전 상대 거래대금 증가","감시",Green)};item{OpportunityCard("✓✓ 추가유입","눌림/횡보 뒤 재유입 확인","매수관심",Amber)};item{OpportunityCard("S SUPER SIGNAL","진입조건까지 검증된 경우에만 승격","검증중",Accent)};item{TradeJournalCard()}}}
@Composable private fun RadarScreen(){val modules=listOf(RadarModule("9AM","08:30~09:00 급등 후보 탐지","분석중","급등 역추적 조건으로 사전감지 검증"),RadarModule("Daily Surge","일중 +5~20% 급등 조기 탐지","연구완료","KRW 4분할 역추적 완료 · 매수지점 연구 단계"),RadarModule("Accumulation","가격보다 먼저 들어오는 거래대금 탐지","분석중","자기 과거 거래대금 대비 유입률 사용"),RadarModule("Entry Lab","조기/눌림/추가유입/돌파 진입 비교","분석중","승률·PF·MDD·최대역행폭 비교"));LazyColumn(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal=14.dp),contentPadding=PaddingValues(top=14.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("레이더","전략별 상태와 근거")};modules.forEach{m->item{Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(m.name,fontWeight=FontWeight.ExtraBold,fontSize=20.sp);StatusBadge(m.state)};Text(m.subtitle,color=Muted);HorizontalDivider(color=Color(0xFF273142));Text(m.detail,fontSize=13.sp)}}}}}}
@Composable private fun ChartScreen(){LazyColumn(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal=14.dp),contentPadding=PaddingValues(top=14.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("차트","✓ → ✓✓ → S와 실제 진입지점을 한 화면에서 확인")};item{Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(20.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("BTC / KRW",fontWeight=FontWeight.ExtraBold,fontSize=22.sp);Box(Modifier.fillMaxWidth().height(220.dp).background(Surface2,RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){Text("자금유입 + 매수지점 데이터 연결 준비",color=Muted)};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("5분","15분","1시간","4시간").forEach{AssistChip(onClick={},label={Text(it)})}}}}};item{TradeJournalCard()}}}
@Composable private fun AssetScreen(){var asset by remember{mutableStateOf("금")};LazyColumn(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal=14.dp),contentPadding=PaddingValues(top=14.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("자산","금·ETF·예금을 한곳에서 탐색")};item{Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("금","ETF","예금").forEach{FilterChip(selected=asset==it,onClick={asset=it},label={Text(it)})}}};item{when(asset){"금"->GoldTimingCard();"ETF"->EtfExplorerCard();else->DepositFinderCard()}}}}
@Composable private fun GoldTimingCard(){Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Column{Text("GOLD 타이밍",fontWeight=FontWeight.ExtraBold,fontSize=20.sp);Text("금 매수환경 레이더",color=Muted,fontSize=12.sp)};StatusBadge("검증전")};Text("국제 금 · 원화 금가격 · 실질금리 · 달러 · 환율",color=Muted,fontSize=13.sp);HorizontalDivider(color=Color(0xFF273142));GoldFactor("국제 금 시세/추세","연결 준비");GoldFactor("원화 기준 금 가격","연결 준비");GoldFactor("단기 조정/과열","연결 준비");GoldFactor("미국 실질금리","연결 준비");GoldFactor("달러·원/달러","연결 준비");HorizontalDivider(color=Color(0xFF273142));Text("환경 불리 → 중립 → 관심구간 → 분할매수 관심 → 추세 확인",fontWeight=FontWeight.Bold,fontSize=12.sp);Text("매수점수는 백테스트 검증 후 활성화",color=Amber,fontSize=11.sp)}}}
@Composable private fun EtfExplorerCard(){var filter by remember{mutableStateOf("전체")};Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("ETF 탐색기",fontWeight=FontWeight.ExtraBold,fontSize=20.sp);Text("수익률·변동성·거래대금·추세 비교",color=Muted,fontSize=12.sp)};StatusBadge("연결준비")};Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("전체","국내","해외").forEach{FilterChip(selected=filter==it,onClick={filter=it},label={Text(it,fontSize=11.sp)})}};HorizontalDivider(color=Color(0xFF273142));GoldFactor("현재가/등락률","실시간 데이터 연결 준비");GoldFactor("1개월·3개월·1년 수익률","계산 준비");GoldFactor("변동성/최대낙폭","계산 준비");GoldFactor("거래대금/추세","계산 준비");GoldFactor("관심 ETF 저장","UI 준비");Text("데이터 연결 후 조건별 정렬·검색·관심목록 제공",color=Accent,fontWeight=FontWeight.Bold,fontSize=11.sp)}}}
@Composable private fun DepositFinderCard(){var months by remember{mutableStateOf("12개월")};var amount by remember{mutableStateOf("10,000,000")};Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(9.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("예금 찾기",fontWeight=FontWeight.ExtraBold,fontSize=20.sp);Text("금리뿐 아니라 실제 받을 금액까지 비교",color=Muted,fontSize=12.sp)};StatusBadge("연결준비")};OutlinedTextField(value=amount,onValueChange={amount=it.filter{c->c.isDigit()||c==','}},label={Text("예치금액")},suffix={Text("원")},singleLine=true,modifier=Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("6개월","12개월","24개월").forEach{FilterChip(selected=months==it,onClick={months=it},label={Text(it,fontSize=11.sp)})}};HorizontalDivider(color=Color(0xFF273142));GoldFactor("은행/저축은행","상품 데이터 연결 준비");GoldFactor("기본·최고 금리","비교 준비");GoldFactor("세후 예상이자","자동 계산 준비");GoldFactor("우대조건","표시 준비");GoldFactor("중도해지 조건","표시 준비");GoldFactor("예금자보호 여부","표시 준비");Text("상품 연결 후 금리·조건·세후수령액 기준으로 정렬",color=Accent,fontWeight=FontWeight.Bold,fontSize=11.sp)}}}
@Composable private fun GoldFactor(name:String,value:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(name,fontSize=12.sp);Text(value,color=Muted,fontSize=11.sp)}}
@Composable private fun AlertScreen(){LazyColumn(Modifier.fillMaxSize().statusBarsPadding().padding(horizontal=14.dp),contentPadding=PaddingValues(top=14.dp,bottom=24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Header("알림","단계별 알림 + 소리/진동 관리")};item{AlertSettingsCard()};item{AlertCard("✓","자금유입","초기 유입 감지")};item{AlertCard("✓✓","매수관심","추가유입 + 구조 확인")};item{AlertCard("S","SUPER SIGNAL","최종 조건은 매수지점 연구 후 확정")}}}
@Composable private fun MarketChip(title:String,value:String,modifier:Modifier=Modifier){Card(modifier=modifier,colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(14.dp)){Column(Modifier.padding(10.dp)){Text(title,fontWeight=FontWeight.Bold);Text(value,color=Muted,fontSize=10.sp,maxLines=1)}}};@Composable private fun OpportunityCard(title:String,body:String,state:String,accent:Color){Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(title,fontWeight=FontWeight.Bold,fontSize=18.sp);Text(body,color=Muted,fontSize=13.sp)};Spacer(Modifier.width(10.dp));androidx.compose.material3.Surface(color=accent.copy(alpha=.15f),shape=RoundedCornerShape(50)){Text(state,color=accent,fontWeight=FontWeight.Bold,fontSize=11.sp,modifier=Modifier.padding(horizontal=10.dp,vertical=6.dp))}}}};@Composable private fun AlertCard(state:String,title:String,detail:String){val c=when(state){"S"->Accent;"✓✓"->Amber;else->Green};Card(colors=CardDefaults.cardColors(containerColor=Surface),shape=RoundedCornerShape(18.dp)){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.spacedBy(12.dp)){androidx.compose.material3.Surface(color=c.copy(alpha=.15f),shape=RoundedCornerShape(12.dp)){Text(state,color=c,fontWeight=FontWeight.ExtraBold,modifier=Modifier.padding(horizontal=12.dp,vertical=8.dp))};Column{Text(title,fontWeight=FontWeight.Bold);Text(detail,color=Muted,fontSize=12.sp)}}}};@Composable private fun SectionTitle(title:String){Text(title,fontSize=20.sp,fontWeight=FontWeight.ExtraBold)};@Composable private fun StatusBadge(state:String){val c=when(state){"연구완료"->Green;"보류"->Red;"분석중"->Amber;"검증전"->Amber;"연결준비"->Accent;else->Muted};androidx.compose.material3.Surface(color=c.copy(alpha=.15f),shape=RoundedCornerShape(50)){Text(state,color=c,fontWeight=FontWeight.Bold,fontSize=11.sp,modifier=Modifier.padding(horizontal=10.dp,vertical=5.dp))}}